export const TOOL_RISK_LEVEL: Record<string, { level: "safe" | "moderate" | "high"; reason: string }> = {
  read_file: { level: "safe", reason: "Reads files from disk. No modifications." },
  write_file: { level: "moderate", reason: "Writes to disk. Can overwrite files." },
  list_files: { level: "safe", reason: "Lists directory contents. Read-only." },
  find_files: { level: "safe", reason: "Searches for files by pattern. Read-only." },
  search_files: { level: "safe", reason: "Searches file contents for a pattern. Read-only." },
  code_review: { level: "safe", reason: "Reviews supplied or current code changes. Read-only." },
  bash_exec: { level: "high", reason: "Executes shell commands. Full system access." },
  web_search: { level: "safe", reason: "Searches the web via API. Read-only." },
  web_extract: { level: "safe", reason: "Extracts readable content from public URLs. Read-only." },
  web_crawl: { level: "safe", reason: "Crawls same-origin public pages with bounded depth. Read-only." },
  fetch_url: { level: "moderate", reason: "Fetches URLs. Can access internal network." },
  http_request: { level: "moderate", reason: "Makes HTTP requests. Can access internal network." },
  browser_action: { level: "high", reason: "Controls a headless browser. Can navigate any site." },
  browser_navigate: { level: "safe", reason: "Navigates a browser for read-only page inspection." },
  browser_snapshot: { level: "safe", reason: "Reads the current browser accessibility snapshot." },
  browser_click: { level: "moderate", reason: "Clicks an element in browser automation." },
  browser_type: { level: "moderate", reason: "Types into a browser field." },
  browser_scroll: { level: "safe", reason: "Scrolls the current browser page for inspection." },
  browser_back: { level: "safe", reason: "Navigates the browser back during inspection." },
  browser_press: { level: "moderate", reason: "Presses a keyboard key in browser automation." },
  browser_get_text: { level: "safe", reason: "Extracts visible page text from the browser." },
  browser_get_links: { level: "safe", reason: "Extracts links from the current browser page." },
  browser_get_images: { level: "safe", reason: "Extracts image metadata from the current browser page." },
  browser_vision: { level: "safe", reason: "Captures and analyzes the current browser page screenshot." },
  browser_cdp: { level: "safe", reason: "Runs allowlisted browser inspection commands." },
  browser_dialog: { level: "safe", reason: "Lists or resolves pending browser dialogs." },
  browser_wait: { level: "safe", reason: "Waits for browser page state during read-only inspection." },
  browser_screenshot: { level: "safe", reason: "Captures a screenshot of the current browser page." },
  browser_console: { level: "safe", reason: "Reads browser console output or evaluates read-only page expressions." },
  take_screenshot: { level: "moderate", reason: "Captures desktop screenshot." },
  memory_search: { level: "safe", reason: "Searches local memory. Read-only." },
  memory_get: { level: "safe", reason: "Reads a memory file. Read-only." },
  memory_gpt: { level: "safe", reason: "Ranks memory results via LLM. Read-only." },
  session_recall: { level: "safe", reason: "Searches past sessions. Read-only." },
  memory_store: { level: "moderate", reason: "Writes to memory. Can modify learned data." },
  memory_delete: { level: "moderate", reason: "Deletes memory entries." },
  documents_list: { level: "safe", reason: "Lists data sources. Read-only." },
  documents_search: { level: "safe", reason: "Searches documents. Read-only." },
  document_get: { level: "safe", reason: "Reads a document. Read-only." },
  document_ingest: { level: "moderate", reason: "Scrapes and stores website content." },
  run_python: { level: "high", reason: "Executes Python scripts. Full system access." },
  run_python_script: { level: "high", reason: "Executes Python with tool access. Sandboxed but still powerful." },
  send_message: { level: "moderate", reason: "Sends messages to external channels." },
  sessions_spawn: { level: "high", reason: "Spawns external coding agents on the host." },
  agent_inbox: { level: "moderate", reason: "Sends messages between agents." },
  board_tasks: { level: "moderate", reason: "Creates and modifies board tasks." },
  call_workflow: { level: "moderate", reason: "Triggers other workflows." },
  schedule_task: { level: "moderate", reason: "Schedules cron-based workflow runs." },
  backup_create: { level: "moderate", reason: "Creates backup snapshots." },
  backup_restore: { level: "high", reason: "Restores backups. Can overwrite database and data." },
  governance_queue: { level: "moderate", reason: "Manages approvals and wakeup queue." },
  sessions_yield: { level: "safe", reason: "Ends current turn with follow-up context." },
  session_todo: { level: "safe", reason: "Manages session-scoped task list." },
  image_view: { level: "safe", reason: "Reads image files. Read-only." },
  image_generate: { level: "moderate", reason: "Generates images via external API (cost)." },
  system_info: { level: "safe", reason: "Reports system stats. Read-only." },
  tool_docs_search: { level: "safe", reason: "Searches tool documentation. Read-only." },
  channel_status: { level: "safe", reason: "Reports channel, model, and voice runtime readiness without exposing secrets. Read-only." },
  channel_directory: { level: "safe", reason: "Lists known channel recipients. Read-only." },
  checkpoint_create: { level: "moderate", reason: "Creates git-backed workspace snapshots." },
  checkpoint_list: { level: "safe", reason: "Lists checkpoints. Read-only." },
  checkpoint_diff: { level: "safe", reason: "Views checkpoint diffs. Read-only." },
  checkpoint_rollback: { level: "high", reason: "Restores filesystem state. Can discard changes." },
  init_experiment: { level: "moderate", reason: "Sets up experiment optimization sessions." },
  run_experiment: { level: "high", reason: "Runs benchmarks and executes code." },
  log_experiment: { level: "moderate", reason: "Records experiment results and git commits." },
  mcp_list: { level: "safe", reason: "Lists MCP servers and tools. Read-only." },
  mcp_call: { level: "moderate", reason: "Executes MCP tool on connected server." },
  mcp_list_resources: { level: "safe", reason: "Lists MCP resources. Read-only." },
  mcp_read_resource: { level: "safe", reason: "Reads MCP resource. Read-only." },
  mcp_list_prompts: { level: "safe", reason: "Lists MCP prompts. Read-only." },
  mcp_get_prompt: { level: "safe", reason: "Reads MCP prompt. Read-only." },
  clarify: { level: "safe", reason: "Asks clarifying question. No side effects." },
  credential_pool: { level: "safe", reason: "Reports credential pool status. Read-only." },
  moa: { level: "safe", reason: "Queries models and synthesizes. Read-only." },
  workflow_templates: { level: "safe", reason: "Lists workflow templates. Read-only." },
  workflow_create: { level: "moderate", reason: "Creates new workflows from templates." },
  schedules_list: { level: "safe", reason: "Lists scheduled jobs. Read-only." },
  webhooks_list:  { level: "safe", reason: "Lists webhooks without secrets. Read-only." },
  webhooks_create: { level: "moderate", reason: "Creates a webhook automation and returns a new secret once." },
  webhooks_rotate_secret: { level: "high", reason: "Rotates a webhook signing secret and returns the new secret once." },
  webhooks_toggle: { level: "moderate", reason: "Enables or disables a webhook automation." },
  webhooks_delete: { level: "high", reason: "Deletes a webhook automation." },
  backup_list: { level: "safe", reason: "Lists backup snapshots. Read-only." },
  backup_verify: { level: "safe", reason: "Verifies backup checksums. Read-only." },
  backup_status: { level: "safe", reason: "Reports backup policy status. Read-only." },
  backup_run_policy: { level: "moderate", reason: "Runs automated backup policy." },
};

export const TOOL_POLICY_PRESETS: Record<string, { label: string; description: string; tools: string[] }> = {
  "safe-readonly": {
    label: "Safe Read-Only",
    description: "Only tools that read data. No modifications, no network access.",
    tools: ["read_file", "list_files", "find_files", "search_files", "code_review", "memory_search", "memory_get", "session_recall",
            "documents_search", "document_get", "documents_list", "pc_specs", "system_info",
            "tool_docs_search", "channel_status", "channel_directory", "web_search", "web_extract", "web_crawl",
            "fetch_url", "browser_navigate", "browser_snapshot", "browser_scroll",
            "browser_back", "browser_get_text", "browser_get_links", "browser_get_images",
            "browser_vision", "browser_cdp", "browser_dialog", "browser_wait", "browser_screenshot", "browser_console",
            "mcp_list", "mcp_list_resources",
            "mcp_read_resource", "mcp_list_prompts", "mcp_get_prompt", "clarify",
            "credential_pool", "moa", "schedules_list", "webhooks_list", "backup_list", "backup_verify",
            "backup_status", "workflow_templates", "checkpoint_list", "checkpoint_diff",
            "image_view"],
  },
  "local-workspace": {
    label: "Local Workspace",
    description: "Read/write local files + memory. No shell or network.",
    tools: ["read_file", "write_file", "list_files", "find_files", "search_files", "code_review", "memory_search", "memory_store",
            "memory_get", "memory_gpt", "session_recall", "session_todo", "documents_search",
            "document_get", "documents_list", "system_info", "tool_docs_search",
            "checkpoint_create", "checkpoint_list", "checkpoint_diff", "checkpoint_rollback",
            "image_view", "clarify", "moa"],
  },
  "network-research": {
    label: "Network Research",
    description: "Web search + URL fetch + local files. No shell or browser automation.",
    tools: ["web_search", "web_extract", "web_crawl", "fetch_url", "http_request",
            "browser_action", "browser_navigate", "browser_snapshot", "browser_click",
            "browser_type", "browser_scroll", "browser_back", "browser_press",
            "browser_get_text", "browser_get_links", "browser_get_images", "browser_vision",
            "browser_cdp", "browser_dialog", "browser_wait", "browser_screenshot", "browser_console",
            "read_file", "write_file", "list_files",
            "find_files", "search_files", "code_review", "memory_search", "memory_store", "memory_get", "memory_gpt",
            "session_recall", "documents_search", "document_get", "documents_list",
            "system_info", "tool_docs_search", "clarify", "moa", "image_view"],
  },
  "full-operator": {
    label: "Full Operator",
    description: "All tools available. Full system and network access.",
    tools: ["*"],
  },
};
