export type AppControlDomain =
  | "docs"
  | "workflow"
  | "scheduler"
  | "data-source"
  | "board"
  | "agent"
  | "channels"
  | "extensions"
  | "skills"
  | "dashboard"
  | "activity"
  | "approvals"
  | "logs"
  | "debug"
  | "maintenance"
  | "security"
  | "metrics"
  | "usage"
  | "settings"
  | "council"
  | "hierarchy"
  | "tags"
  | "memory"
  | "live"
  | "checkpoint";

export type BuiltinIntentClass = "app_read";

export type BuiltinIntentEntry = {
  id: string;
  command: string;
  intentClass: BuiltinIntentClass;
  aliases: string[];
  domains: AppControlDomain[];
  keywords: string[];
  examplePhrases?: string[];
  surfaceDescription?: string;
  defaultForDomain?: boolean;
  compoundSlots?: string[];
  useWhen?: string[];
  notWhen?: string[];
  confusableWith?: string[];
  contrastNotes?: string[];
};

export const BUILTIN_INTENTS: BuiltinIntentEntry[] = [
  {
    id: "orientation.triple",
    command: "show orientation summary",
    intentClass: "app_read",
    aliases: [
      "before i touch anything, what is already on autopilot, what is pending, and what feels off?",
      "before i touch anything what is already on autopilot what is pending and what feels off",
      "what is already on autopilot, what is pending, and what feels off?",
      "what is already on autopilot what is pending and what feels off",
      "before i do anything here, what is already on autopilot, what is pending, and what feels off?",
      "before i do anything here what is already on autopilot what is pending and what feels off",
    ],
    domains: ["dashboard", "workflow", "approvals", "maintenance"],
    keywords: ["autopilot", "pending", "feels off"],
    surfaceDescription: "orientation summary across autopilot, approvals, and maintenance status",
    compoundSlots: ["orientation"],
  },
  {
    id: "orientation.support",
    command: "show support orientation",
    intentClass: "app_read",
    aliases: [
      "which channels are alive, who can help, and where do i tweak defaults?",
      "which channels are alive who can help and where do i tweak defaults",
      "before i change anything, which channels are alive and where do i tweak defaults?",
      "before i change anything which channels are alive and where do i tweak defaults",
      "which channels are alive and where do i tweak defaults?",
      "which channels are alive and where do i tweak defaults",
      "what channels are alive, who can help, and where do i tweak defaults?",
      "what channels are alive who can help and where do i tweak defaults",
      "help me get oriented: which channels are alive, who can help, and where do i tweak defaults?",
      "just orient me: which channels are alive, who can help, and where do i tweak defaults?",
      "help me understand what is connected and who can work on things",
      "what is connected and who can work on things",
    ],
    domains: ["channels", "agent", "settings"],
    keywords: ["channels", "connected", "alive", "help", "who can work", "defaults"],
    surfaceDescription: "orientation summary across connected channels, available agents, and configuration defaults",
    compoundSlots: ["orientation"],
  },
  {
    id: "dashboard.summary",
    command: "show dashboard",
    intentClass: "app_read",
    aliases: [
      "dashboard",
      "system overview",
      "status overview",
      "give me a quick system overview",
      "give me the quick big picture",
      "hows everything looking overall",
      "how's everything looking overall",
      "how are things",
      "what's the system looking like right now",
      "can you just sanity check things and tell me what stands out",
      "i need the lay of the land before i touch anything",
      "give me the big picture before i mess with anything",
      "what should i pay attention to first around here",
      "i want to get a feel for the system without changing anything",
    ],
    domains: ["dashboard"],
    keywords: ["dashboard", "system", "overview", "status"],
    surfaceDescription: "system overview, status, machine info, and the big picture before touching anything",
    defaultForDomain: true,
    useWhen: ["big picture", "overall status", "lay of the land", "quick overview"],
    notWhen: ["what has been firing a lot", "what looks off operationally", "how busy has it been"],
    confusableWith: ["activity.summary", "maintenance.summary", "usage.summary"],
    contrastNotes: [
      "use dashboard for the broad system picture before touching anything",
      "use activity for run history, maintenance for what is off, and usage for traffic or load",
    ],
    examplePhrases: [
      "what's the system looking like right now?",
      "how's everything looking overall?",
      "how are things?",
      "can you just sanity check things and tell me what stands out?",
      "i need the lay of the land before i touch anything",
      "give me the big picture before i mess with anything",
      "what should i pay attention to first around here",
      "i want to get a feel for the system without changing anything",
    ],
  },
  {
    id: "activity.summary",
    command: "show activity",
    intentClass: "app_read",
    aliases: [
      "activity",
      "recent activity",
      "show me recent activity",
      "anything been firing a lot",
      "has anything been running a lot today",
      "anything running right now",
      "what is running",
    ],
    domains: ["activity"],
    keywords: ["activity", "recent", "lately", "runs", "history", "running", "executed", "firing"],
    surfaceDescription: "recent executions, run history, and what has been running lately",
    defaultForDomain: true,
    useWhen: ["recent runs", "firing a lot", "what is running", "execution history"],
    notWhen: ["how busy has this been", "where is spend landing", "big picture"],
    confusableWith: ["usage.summary", "dashboard.summary"],
    contrastNotes: [
      "use activity for workflow executions and recent runs",
      "use usage for traffic or request volume rather than execution history",
    ],
    examplePhrases: ["has anything been running a lot today?", "anything been firing a lot?", "anything running right now?", "what is running?"],
  },
  {
    id: "approvals.summary",
    command: "show approvals",
    intentClass: "app_read",
    aliases: [
      "approvals",
      "approval queue",
      "what is pending",
      "what approvals need attention",
      "is there anything stuck waiting for me",
      "is there anything waiting on me",
      "what is waiting on me",
      "what is waiting on me right now",
      "what approvals are waiting",
      "is there anything waiting on approval right now",
      "can you show me the approvals",
      "is there anything waiting on me or needing approval",
    ],
    domains: ["approvals"],
    keywords: ["approval", "approvals", "pending", "attention", "waiting", "stuck"],
    surfaceDescription: "approval queue, pending approvals, and things waiting for review",
    defaultForDomain: true,
    examplePhrases: [
      "is there anything waiting on approval right now?",
      "is there anything stuck waiting for me?",
      "is there anything waiting on me?",
      "what approvals are waiting?",
      "is there anything waiting on me or needing approval?",
    ],
  },
  {
    id: "logs.summary",
    command: "show recent logs",
    intentClass: "app_read",
    aliases: ["logs", "recent logs", "what do the recent logs show", "do the logs look weird lately", "do the logs look weird", "anything weird in the logs", "give me the logs"],
    domains: ["logs"],
    keywords: ["log", "logs", "tail", "weird", "odd"],
    surfaceDescription: "recent log lines, log tail, and weird or error-looking log output",
    defaultForDomain: true,
    examplePhrases: ["do the logs look weird lately?", "anything weird in the logs?"],
  },
  {
    id: "debug.summary",
    command: "show debug",
    intentClass: "app_read",
    aliases: ["debug", "debug summary", "debug snapshot"],
    domains: ["debug"],
    keywords: ["debug", "debugger", "snapshot"],
    surfaceDescription: "debug snapshot, debugger state, and internal diagnostics",
    defaultForDomain: true,
  },
  {
    id: "maintenance.summary",
    command: "show maintenance",
    intentClass: "app_read",
    aliases: [
      "maintenance",
      "maintenance status",
      "show maintenance status",
      "does anything need ops attention",
      "is anything broken",
      "what looks off right now",
      "what looks unhealthy",
      "what looks unhealthy right now",
      "what feels off",
      "what feels off today",
      "what might be broken",
      "what should i keep an eye on operationally today",
    ],
    domains: ["maintenance"],
    keywords: ["maintenance", "health", "ops", "unhealthy"],
    surfaceDescription: "health checks, ops health, maintenance status, and whether anything feels off or broken",
    defaultForDomain: true,
    useWhen: ["ops attention", "what looks off", "what looks unhealthy", "broken", "operational watchlist"],
    notWhen: ["recent executions", "traffic volume", "spend analysis"],
    confusableWith: ["dashboard.summary", "activity.summary", "usage.summary"],
    contrastNotes: [
      "use maintenance when the user wants health, risk, or what looks wrong",
      "use activity for recent runs and dashboard for the broad overview",
    ],
    examplePhrases: ["does anything need ops attention?", "is anything broken?", "what feels off today?", "what might be broken?"],
  },
  {
    id: "security.summary",
    command: "show security",
    intentClass: "app_read",
    aliases: [
      "security",
      "security report",
      "security summary",
      "anything sketchy i should know about",
      "anything sketchy going on",
      "anything i should worry about on the security side lately",
      "what should i worry about",
      "what does security look like",
      "give me a security report",
    ],
    domains: ["security"],
    keywords: ["security", "audit", "risk", "worry", "red flag", "red flags", "sketchy", "concerning"],
    surfaceDescription: "security audit, risks, vulnerabilities, and anything sketchy or concerning",
    defaultForDomain: true,
    examplePhrases: ["anything i should worry about on the security side lately?", "anything sketchy i should know about?", "anything sketchy going on?", "what should i worry about?"],
  },
  {
    id: "metrics.summary",
    command: "show metrics",
    intentClass: "app_read",
    aliases: [
      "metrics",
      "cost analysis",
      "show me cost analysis",
      "what do the metrics look like today",
      "what are the top providers and workflows this week",
      "where is most of the cost landing lately",
      "where's most of the spend and usage going this week",
    ],
    domains: ["metrics"],
    keywords: ["metric", "metrics", "cost", "spend", "provider", "providers", "landing"],
    surfaceDescription: "costs, spend, provider usage, and where usage or spend is landing",
    defaultForDomain: true,
    useWhen: ["spend", "cost landing", "top providers", "where is cost going"],
    notWhen: ["how busy has it been", "recent executions", "big picture"],
    confusableWith: ["usage.summary", "activity.summary"],
    contrastNotes: [
      "use metrics for spend, providers, and cost concentration",
      "use usage for load or traffic and activity for execution history",
    ],
    examplePhrases: ["where's most of the spend and usage going this week?", "where is most of the cost landing lately?"],
  },
  {
    id: "usage.summary",
    command: "show usage",
    intentClass: "app_read",
    aliases: ["usage", "usage summary", "how are we doing today on usage", "has this been busy recently", "how busy have we been", "how busy has this app been today", "how busy has this thing been lately"],
    domains: ["usage"],
    keywords: ["usage", "busy", "volume", "traffic"],
    surfaceDescription: "traffic, volume, and how busy the app has been",
    defaultForDomain: true,
    useWhen: ["busy lately", "traffic", "volume", "load"],
    notWhen: ["where is spend landing", "recent executions", "ops attention"],
    confusableWith: ["activity.summary", "metrics.summary", "maintenance.summary"],
    contrastNotes: [
      "use usage for overall app load or traffic volume",
      "use activity for executions and metrics for spend or provider cost",
    ],
    examplePhrases: ["how busy has this app been today?", "has this been busy recently?", "how busy have we been?"],
  },
  {
    id: "settings.summary",
    command: "show settings",
    intentClass: "app_read",
    aliases: [
      "settings",
      "config",
      "configuration",
      "what can the settings page help me control",
      "where would i tweak the app defaults and config",
      "where do i tweak defaults",
      "show me where i would tweak defaults if i wanted quieter telemetry",
    ],
    domains: ["settings"],
    keywords: ["settings", "config", "configuration", "defaults", "tweak"],
    surfaceDescription: "configuration, app defaults, and where to tweak settings",
    defaultForDomain: true,
    useWhen: ["tweak defaults", "app config", "where do i change defaults"],
    notWhen: ["which channels are alive", "who can help", "recent activity"],
    confusableWith: ["channels.status"],
    contrastNotes: [
      "use settings when the user wants config or default behavior",
      "use channels when the user wants connection or channel status",
    ],
    examplePhrases: [
      "where would i tweak the app defaults and config?",
      "where do i tweak defaults?",
      "show me where i would tweak defaults if i wanted quieter telemetry",
    ],
  },
  {
    id: "docs.list",
    command: "list docs",
    intentClass: "app_read",
    aliases: ["docs", "documents", "data sources", "what data sources do i have", "what docs have i uploaded", "what source material do we have in here", "what are we using for docs and source material here", "what source material is in the workspace", "what source material is in the workspace right now"],
    domains: ["docs", "data-source"],
    keywords: ["docs", "document", "documents", "source", "sources", "material", "data source"],
    surfaceDescription: "documents, uploaded files, data sources, and source material",
    defaultForDomain: true,
    useWhen: ["source material", "documents in workspace", "uploaded docs", "data sources"],
    notWhen: ["automations", "workflows", "agents"],
    confusableWith: ["workflows.list"],
    contrastNotes: [
      "use docs for source material and data sources",
      "use workflows for automations or things already on autopilot",
    ],
    examplePhrases: ["what are we using for docs and source material here?", "what source material do we have in here?"],
  },
  {
    id: "docs.help",
    command: "how do i use docs",
    intentClass: "app_read",
    aliases: [
      "how do i use docs",
      "how can i use docs",
      "how do i use the docs",
      "how can i use the docs",
      "how do i use documentation",
      "how can i use documentation",
    ],
    domains: ["docs", "data-source"],
    keywords: ["docs", "document", "documents", "source", "sources"],
    surfaceDescription: "help using the docs and data source features",
  },
  {
    id: "data-source.help",
    command: "how do i use data source",
    intentClass: "app_read",
    aliases: [
      "how do i use data source",
      "how do i use data sources",
      "how do i use the data source",
      "how do i use the data sources",
      "how can i use data source",
      "how can i use data sources",
      "how can i use the data source",
      "how can i use the data sources",
    ],
    domains: ["data-source", "docs"],
    keywords: ["data source", "data sources", "documents", "uploads"],
    surfaceDescription: "help using data sources, uploads, and scraping",
  },
  {
    id: "docs.summary",
    command: "show docs summary",
    intentClass: "app_read",
    aliases: ["show docs summary"],
    domains: ["docs", "data-source"],
    keywords: ["docs summary", "document summary", "data source summary"],
    surfaceDescription: "docs summary, stored data sources, and docs-related workflow summary",
  },
  {
    id: "workflows.list",
    command: "list workflows",
    intentClass: "app_read",
    aliases: [
      "workflow",
      "workflows",
      "my workflows",
      "our workflows",
      "what workflows do we have",
      "which workflows are live right now",
      "what have we got set up to automate work",
      "do we already have anything automating triage work and if not what would you create",
      "what is already on autopilot",
      "what is already on autopilot here",
      "what is on autopilot here",
      "whats available to automate things",
      "what's available to automate things",
      "what flows are active around here right now",
      "what automations do we have running around here",
      "i want to see my workflows",
    ],
    domains: ["workflow"],
    keywords: ["workflow", "workflows", "automation", "automations", "flow", "flows", "automate"],
    surfaceDescription: "workflows, automations, pipelines, and what is already on autopilot",
    defaultForDomain: true,
    useWhen: ["autopilot", "automation", "flows", "what is set up to automate work"],
    notWhen: ["source material", "uploaded docs", "documents in workspace"],
    confusableWith: ["docs.list", "activity.summary"],
    contrastNotes: [
      "use workflows for automations and autopilot behavior",
      "use docs for source material and activity for recent runs",
    ],
    examplePhrases: [
      "what automations do we have running around here?",
      "what have we got set up to automate work?",
      "what's available to automate things?",
      "do we already have anything automating triage work, and if not what would you create?",
      "what is on autopilot here?",
    ],
  },
  {
    id: "workflows.help",
    command: "how do i use workflow",
    intentClass: "app_read",
    aliases: [
      "how do i use workflow",
      "how do i use workflows",
      "how do i use workflow here",
      "how do i use workflows here",
      "how can i use workflow",
      "how can i use workflows",
      "how can i use workflow here",
      "how can i use workflows here",
    ],
    domains: ["workflow"],
    keywords: ["workflow", "workflows", "automation"],
    surfaceDescription: "help using workflows and automations",
  },
  {
    id: "workflows.templates",
    command: "list workflow templates",
    intentClass: "app_read",
    aliases: [
      "what workflow templates can you use right now",
      "what workflow templates are available",
      "can you show me what workflow templates are available",
      "what are all my templates",
      "what are all the templates i have",
      "show all my templates",
      "list workflow templates",
      "show workflow templates",
    ],
    domains: ["workflow"],
    keywords: ["workflow", "workflows", "template", "templates"],
    surfaceDescription: "available workflow templates the app can use right now",
    examplePhrases: ["what workflow templates can you use right now?"],
  },
  {
    id: "agents.list",
    command: "list agents",
    intentClass: "app_read",
    aliases: [
      "agent",
      "agents",
      "my agents",
      "our agents",
      "which agents exist",
      "what agents do we have",
      "who can help",
      "who can help me if i get stuck",
      "who do i even have available to help",
      "who can help me with this",
      "who's available on the agent side right now",
      "who do we have available to work with",
      "who is available and which of them has the right skills for incident cleanup",
    ],
    domains: ["agent"],
    keywords: ["agent", "agents", "available"],
    surfaceDescription: "available agents, workers, and who can help",
    defaultForDomain: true,
    useWhen: ["who can help", "available agents", "workers available"],
    notWhen: ["approval queue", "settings defaults", "org membership"],
    confusableWith: ["approvals.summary", "org.active"],
    contrastNotes: [
      "use agents when the user wants helpers or available workers",
      "use approvals for pending actions and org for current team membership",
    ],
    examplePhrases: [
      "who do we have available to work with?",
      "who do i even have available to help?",
      "who can help me with this?",
      "who is available and which of them has the right skills for incident cleanup?",
    ],
  },
  {
    id: "agents.skills.main",
    command: "list all skills for agent main agent",
    intentClass: "app_read",
    aliases: [
      "what skills is main agent using now",
      "what skills is main agent using",
    ],
    domains: ["agent"],
    keywords: ["main agent", "skills", "capabilities", "extensions"],
    surfaceDescription: "skill packs and enabled capabilities for main agent",
  },
  {
    id: "org.active",
    command: "show org",
    intentClass: "app_read",
    aliases: [
      "show org",
      "my org",
      "current org",
      "active org",
      "what org is active",
      "who is in the active organization",
      "who's on that org",
      "who's on that org right now",
      "who is on that org",
      "who is on that org right now",
      "who is on the org",
      "who is on the current org",
      "who is on the current org right now",
      "what team are we working in again",
      "which organization are we operating under at the moment",
    ],
    domains: ["council", "hierarchy"],
    keywords: ["org", "organization", "team", "active", "members"],
    surfaceDescription: "active organization membership and current working team",
    defaultForDomain: true,
    useWhen: ["who is on the current org", "active org", "team membership"],
    notWhen: ["debate", "vote", "deliberate", "where do i go for a decision"],
    confusableWith: ["council.help", "org.list"],
    contrastNotes: [
      "use org.active for the current team or member list",
      "use council when the user wants debate, voting, or deliberation",
    ],
    examplePhrases: ["what team are we working in again?", "who's on that org right now?"],
  },
  {
    id: "org.list",
    command: "show organizations",
    intentClass: "app_read",
    aliases: [
      "org",
      "orgs",
      "organization",
      "organizations",
      "hierarchy",
      "show organizations",
      "what is in the hierarchy right now",
      "show me the hierarchy organizations",
    ],
    domains: ["council", "hierarchy"],
    // "organizations" (plural) scores higher than org.active's single "org" → list wins when plural is used
    keywords: ["org", "organization", "organizations", "hierarchy"],
    surfaceDescription: "organization hierarchy and all organizations in the tree",
    useWhen: ["show organizations", "hierarchy", "list orgs"],
    notWhen: ["who is on the current org", "where do i go to debate something"],
    confusableWith: ["org.active", "council.help"],
    contrastNotes: [
      "use org.list for the hierarchy or all organizations",
      "use org.active for current membership and council for deliberation",
    ],
  },
  {
    id: "tasks.list",
    command: "list tasks",
    intentClass: "app_read",
    aliases: [
      "task",
      "tasks",
      "my tasks",
      "our tasks",
      "what are my tasks",
      "list down my tasks",
      "show board",
      "show boards",
      "what is on the board right now",
      "show me the board tasks",
      "what's on my plate right now",
      "help me check my tasks",
      "what's sitting on the board for me today",
    ],
    domains: ["board"],
    keywords: ["task", "tasks", "board", "plate"],
    surfaceDescription: "board tasks, what is on the board, and what is on my plate",
    defaultForDomain: true,
    examplePhrases: ["what's on my plate right now?"],
  },
  {
    id: "tasks.pending",
    command: "list pending tasks",
    intentClass: "app_read",
    aliases: [
      "open tasks",
      "pending tasks",
      "what tasks are open",
      "which tasks are open",
    ],
    domains: ["board"],
    keywords: ["task", "tasks", "board", "open", "pending"],
    surfaceDescription: "open or pending board tasks",
  },
  {
    id: "tasks.completed",
    command: "list completed tasks",
    intentClass: "app_read",
    aliases: [
      "completed tasks",
      "done tasks",
      "finished tasks",
      "what tasks are done",
      "which tasks are done",
    ],
    domains: ["board"],
    keywords: ["task", "tasks", "board", "done", "completed", "finished"],
    surfaceDescription: "completed or finished board tasks",
  },
  {
    id: "schedules.list",
    command: "list schedules",
    intentClass: "app_read",
    aliases: ["schedule", "schedules", "what schedules do we have live", "what schedules do we have live right now", "which cron jobs are live", "anything on a timer at the moment"],
    domains: ["scheduler"],
    keywords: ["schedule", "schedules", "cron", "timer", "timers"],
    surfaceDescription: "scheduled workflows, cron jobs, and timers",
    defaultForDomain: true,
    examplePhrases: ["anything on a timer at the moment?"],
  },
  {
    id: "webhooks.list",
    command: "list webhooks",
    intentClass: "app_read",
    aliases: [
      "webhooks", "list webhook automations", "show webhooks", "show webhook automations",
      "list automations", "show automations", "automations",
      "what webhooks do we have", "which webhooks are active", "show my webhooks",
      "list my webhooks", "what automations do i have",
    ],
    domains: ["scheduler"],
    keywords: ["webhook", "webhooks", "automation", "automations"],
    surfaceDescription: "webhook automations and their active status",
    defaultForDomain: false,
    examplePhrases: ["what webhooks do we have?", "list automations"],
  },
  {
    id: "workspace.list",
    command: "workspace root",
    intentClass: "app_read",
    aliases: [
      "workspace root",
      "list workspace root",
      "show workspace root",
      "what files do i have at the workspace root",
      "what files are in my workspace root",
    ],
    domains: [],
    keywords: ["workspace root"],
    surfaceDescription: "files and directories at the workspace root",
  },
  {
    id: "system.specs",
    command: "show system specs",
    intentClass: "app_read",
    aliases: [
      "show system specs",
      "system specs",
      "what are my cpu and ram specs",
      "cpu and ram specs",
      "do you know my cpu and ram specs",
    ],
    domains: [],
    keywords: ["system specs", "cpu and ram specs"],
    surfaceDescription: "host machine CPU and RAM specs",
  },
  {
    id: "channels.status",
    command: "channel status",
    intentClass: "app_read",
    aliases: [
      "channels",
      "channel status",
      "what channels are connected",
      "which channels are connected",
      "which channels are alive",
      "which channels do we have live",
      "what channels are alive",
    ],
    domains: ["channels"],
    keywords: ["channel", "channels", "telegram", "slack", "discord", "connect", "alive", "live"],
    surfaceDescription: "channel connections and which channels are connected or alive",
    defaultForDomain: true,
    useWhen: ["which channels are alive", "connected channels", "channel status"],
    notWhen: ["where do i tweak defaults", "show config summary"],
    confusableWith: ["settings.summary"],
    contrastNotes: [
      "use channels for connection or live-channel status",
      "use settings for defaults, config, and app behavior changes",
    ],
  },
  {
    id: "channels.summary",
    command: "show channels",
    intentClass: "app_read",
    aliases: ["show channels", "show channels summary"],
    domains: ["channels"],
    keywords: ["channels summary", "channel summary"],
    surfaceDescription: "full channel summary including WebChat and webhook readiness",
  },
  {
    id: "channels.help",
    command: "how do i use channels",
    intentClass: "app_read",
    aliases: [
      "how do i use channels",
      "how can i use channels",
      "how do i use the channels",
      "how can i use the channels",
    ],
    domains: ["channels"],
    keywords: ["channel", "channels", "telegram", "wire", "setup"],
    surfaceDescription: "help setting up or using messaging channels",
  },
  {
    id: "channels.telegram_setup",
    command: "show setup for extension Telegram",
    intentClass: "app_read",
    aliases: ["show me how to wire up telegram", "how would i wire telegram if i need it"],
    domains: ["channels"],
    keywords: ["telegram", "wire", "setup"],
    surfaceDescription: "Telegram channel setup instructions",
  },
  {
    id: "extensions.list",
    command: "list extensions",
    intentClass: "app_read",
    aliases: [
      "extensions",
      "show extensions",
      "list extensions",
      "show extensions tab",
      "plugins",
      "show plugins",
      "list plugins",
      "show plugins tab",
      "what extensions do i have",
      "what plugins do i have",
    ],
    domains: ["extensions"],
    keywords: ["extension", "extensions", "plugin", "plugins", "extension catalog", "plugin catalog"],
    surfaceDescription: "installed extensions, plugin catalog, and global or agent extension state",
    defaultForDomain: true,
    useWhen: ["show extensions", "list plugins", "extension catalog", "plugin state"],
    notWhen: ["show agent skills", "how do i wire telegram", "system overview"],
    confusableWith: ["skills.list", "channels.telegram_setup", "dashboard.summary"],
    contrastNotes: [
      "use extensions for plugin inventory, global enablement, runtime-backed status, and per-agent attachment",
      "use skills for skill packs and channels setup for connector wiring guidance",
    ],
  },
  {
    id: "extensions.runtime",
    command: "show extension runtime status",
    intentClass: "app_read",
    aliases: [
      "show extension runtime status",
      "extensions runtime status",
      "show extension runtime",
      "extension runtime",
      "show extension runtime summary",
    ],
    domains: ["extensions"],
    keywords: ["extension runtime", "extensions runtime", "plugin runtime"],
    surfaceDescription: "extension runtime hooks, runtime-backed modules, and live extension status",
  },
  {
    id: "skills.list",
    command: "list skills for agent main",
    intentClass: "app_read",
    aliases: [
      "skills",
      "show skills",
      "list skills",
      "show skills tab",
      "show skill packs",
      "list skill packs",
      "what skills are available",
    ],
    domains: ["skills"],
    keywords: ["skill pack", "skill packs", "skills tab", "skills page", "skill catalog"],
    surfaceDescription: "skill packs, enabled capabilities, and the current agent skill catalog",
    defaultForDomain: true,
    useWhen: ["show skills", "skill catalog", "list skill packs"],
    notWhen: ["show plugins", "show agent list", "creative skill advice"],
    confusableWith: ["extensions.list", "agents.list"],
    contrastNotes: [
      "use skills for skill packs and capability inventory",
      "use extensions for plugins and agents for who is available",
    ],
  },
  {
    id: "skills.external_list",
    command: "list external skill packs",
    intentClass: "app_read",
    aliases: [
      "list external skill packs",
      "show external skill packs",
      "list installed skill packs",
      "show installed skill packs",
      "what external skill packs are installed",
      "what installed skill packs do we have",
    ],
    domains: ["skills"],
    keywords: ["external skill packs", "installed skill packs", "skill pack catalog"],
    surfaceDescription: "externally installed skill packs and their source locations",
    useWhen: ["list external skill packs", "show installed skill packs"],
    notWhen: ["list agent skills", "show extension catalog"],
    confusableWith: ["skills.list", "extensions.list"],
    contrastNotes: [
      "use external skill packs for installed local or remote skill-pack bundles",
      "use skills list for the default agent's full available skill catalog",
    ],
  },
  {
    id: "boards.help",
    command: "how do i use board",
    intentClass: "app_read",
    aliases: [
      "how do i use board",
      "how do i use boards",
      "how do i use board here",
      "how do i use boards here",
      "how can i use board",
      "how can i use boards",
      "how can i use board here",
      "how can i use boards here",
    ],
    domains: ["board"],
    keywords: ["board", "task", "tasks"],
    surfaceDescription: "help using the board and task surfaces",
  },
  {
    id: "tags.summary",
    command: "show tags",
    intentClass: "app_read",
    aliases: [
      "tags",
      "show tags",
      "list tags",
      "show tags summary",
      "show tags tab",
    ],
    domains: ["tags"],
    keywords: ["tag", "tags", "labels"],
    surfaceDescription: "tag inventory, tag usage, and the current tagging summary",
    defaultForDomain: true,
    useWhen: ["show tags", "list tags", "tag usage"],
    notWhen: ["taglines", "marketing slogans", "brainstorming"],
    contrastNotes: ["do not use tags for creative requests about taglines or slogans"],
  },
  {
    id: "memory.summary",
    command: "show memory",
    intentClass: "app_read",
    aliases: [
      "memory",
      "show memory",
      "show memory tab",
      "show memory status",
      "memory status",
      "memory summary",
    ],
    domains: ["memory"],
    keywords: ["memory summary", "memory status", "memory tab", "memory page"],
    surfaceDescription: "memory inventory, recall readiness, embedding status, and rollup coverage",
    defaultForDomain: true,
    useWhen: ["show memory", "memory status", "memory summary"],
    notWhen: ["remember this", "recall from memory", "search memory for"],
    confusableWith: ["memory.timeline"],
    contrastNotes: [
      "use memory.summary for the memory surface itself",
      "use memory.timeline for recent memory entries and search/recall commands for retrieval",
    ],
  },
  {
    id: "memory.timeline",
    command: "show memory timeline",
    intentClass: "app_read",
    aliases: [
      "show memory timeline",
      "list memory timeline",
      "memory timeline",
    ],
    domains: ["memory"],
    keywords: ["memory timeline", "memory history"],
    surfaceDescription: "recent memory entries and timeline view",
  },
  {
    id: "live.summary",
    command: "show live",
    intentClass: "app_read",
    aliases: [
      "live",
      "show live",
      "show live tab",
      "live status",
    ],
    domains: ["live"],
    keywords: ["live tab", "live page", "live status"],
    surfaceDescription: "live view routing and the current live activity surface",
    defaultForDomain: true,
  },
  {
    id: "council.help",
    command: "how do i use council",
    intentClass: "app_read",
    aliases: [
      "what is the council for",
      "what's council actually for",
      "how do i use council",
      "where would i go to debate something",
      "where do i go to vote on something",
      "how does the team debate things",
      "where do i go if i need a debate",
      "if i needed the team to debate something where would i do that",
      "where would i go if i needed the team to debate one of those decisions",
      "what does the council tab do",
      "where do i go if the team needs to debate something",
      "i need the team to decide something",
      "i need the team to make a decision",
      "the team needs to decide something",
      "who reports to whom and where do i ask council",
      "who reports to whom and where do i ask council?",
    ],
    domains: ["council"],
    keywords: ["council", "vote", "debate", "decision", "deliberate"],
    surfaceDescription: "help using council, debate, and voting features",
    useWhen: ["debate", "vote", "deliberate", "where do i go for a decision"],
    notWhen: ["who is on the org", "what org is active", "show hierarchy"],
    confusableWith: ["org.active", "org.list"],
    contrastNotes: [
      "use council when the user wants discussion, voting, or deliberation",
      "use org or hierarchy when the user wants team membership or structure",
    ],
  },
  {
    id: "extensions.help",
    command: "how do i use extensions",
    intentClass: "app_read",
    aliases: [
      "how do i use extensions",
      "how do i use the extensions",
      "how can i use extensions",
      "how can i use the extensions",
      "how do i use plugins",
      "how can i use plugins",
    ],
    domains: ["extensions"],
    keywords: ["extensions", "extension", "plugins", "plugin"],
    surfaceDescription: "help using extensions, plugins, and per-agent extension attachment",
  },
  {
    id: "skills.help",
    command: "how do i use skills",
    intentClass: "app_read",
    aliases: [
      "how do i use skills",
      "how do i use the skills",
      "how can i use skills",
      "how can i use the skills",
      "how do i use skill packs",
      "how can i use skill packs",
    ],
    domains: ["skills"],
    keywords: ["skills", "skill", "skill packs", "capabilities"],
    surfaceDescription: "help using skills, skill packs, and agent capability assignment",
  },
  {
    id: "dashboard.help",
    command: "how do i use dashboard",
    intentClass: "app_read",
    aliases: [
      "how do i use dashboard",
      "how do i use the dashboard",
      "how can i use dashboard",
      "how can i use the dashboard",
    ],
    domains: ["dashboard"],
    keywords: ["dashboard"],
    surfaceDescription: "help using the dashboard",
  },
  {
    id: "activity.help",
    command: "how do i use activity",
    intentClass: "app_read",
    aliases: ["how do i use activity", "how can i use activity"],
    domains: ["activity"],
    keywords: ["activity"],
    surfaceDescription: "help using activity and run history",
  },
  {
    id: "approvals.help",
    command: "how do i use approvals",
    intentClass: "app_read",
    aliases: ["how do i use approvals", "how can i use approvals"],
    domains: ["approvals"],
    keywords: ["approvals", "approval"],
    surfaceDescription: "help using approvals",
  },
  {
    id: "logs.help",
    command: "how do i use logs",
    intentClass: "app_read",
    aliases: ["how do i use logs", "how can i use logs"],
    domains: ["logs"],
    keywords: ["logs", "log"],
    surfaceDescription: "help using logs",
  },
  {
    id: "debug.help",
    command: "how do i use debug",
    intentClass: "app_read",
    aliases: ["how do i use debug", "how can i use debug"],
    domains: ["debug"],
    keywords: ["debug"],
    surfaceDescription: "help using debug",
  },
  {
    id: "maintenance.help",
    command: "how do i use maintenance",
    intentClass: "app_read",
    aliases: ["how do i use maintenance", "how can i use maintenance"],
    domains: ["maintenance"],
    keywords: ["maintenance", "health"],
    surfaceDescription: "help using maintenance and health views",
  },
  {
    id: "security.help",
    command: "how do i use security",
    intentClass: "app_read",
    aliases: ["how do i use security", "how can i use security"],
    domains: ["security"],
    keywords: ["security"],
    surfaceDescription: "help using security views",
  },
  {
    id: "metrics.help",
    command: "how do i use metrics",
    intentClass: "app_read",
    aliases: [
      "how do i use metrics",
      "how do i use the metrics",
      "how do i use the metrics tab",
      "how can i use metrics",
      "how can i use the metrics",
      "how can i use the metrics tab",
    ],
    domains: ["metrics"],
    keywords: ["metrics", "cost"],
    surfaceDescription: "help using metrics and cost analysis",
  },
  {
    id: "usage.help",
    command: "how do i use usage",
    intentClass: "app_read",
    aliases: [
      "how do i use usage",
      "how do i use the usage",
      "how do i use the usage tab",
      "how can i use usage",
      "how can i use the usage",
      "how can i use the usage tab",
    ],
    domains: ["usage"],
    keywords: ["usage"],
    surfaceDescription: "help using usage views",
  },
  {
    id: "settings.help",
    command: "how do i use settings",
    intentClass: "app_read",
    aliases: ["how do i use settings", "how can i use settings"],
    domains: ["settings"],
    keywords: ["settings", "config"],
    surfaceDescription: "help using settings and configuration",
  },
  {
    id: "tags.help",
    command: "how do i use tags",
    intentClass: "app_read",
    aliases: [
      "how do i use tags",
      "how do i use the tags",
      "how can i use tags",
      "how can i use the tags",
    ],
    domains: ["tags"],
    keywords: ["tag", "tags"],
    surfaceDescription: "help using tags and labels",
  },
  {
    id: "memory.help",
    command: "how do i use memory",
    intentClass: "app_read",
    aliases: [
      "how do i use memory",
      "how do i use the memory",
      "how can i use memory",
      "how can i use the memory",
    ],
    domains: ["memory"],
    keywords: ["memory", "memory timeline", "memory recall"],
    surfaceDescription: "help using the memory surface, memory timeline, and recall tools",
  },
  {
    id: "live.help",
    command: "how do i use live",
    intentClass: "app_read",
    aliases: [
      "how do i use live",
      "how do i use the live tab",
      "how can i use live",
      "how can i use the live tab",
    ],
    domains: ["live"],
    keywords: ["live", "live tab", "live page"],
    surfaceDescription: "help using the live surface and its activity redirect",
  },
  {
    id: "commands.palette",
    command: "show command palette",
    intentClass: "app_read",
    aliases: [
      "show command palette",
      "show commands",
      "list commands",
      "what commands are available",
      "what can i ask you",
      "help commands",
      "show me what i can ask",
      "what commands do you know",
      "command help",
      "show available commands",
    ],
    domains: ["dashboard"],
    keywords: ["command", "commands", "palette", "available commands"],
    surfaceDescription: "list of all available built-in commands and example phrases",
    examplePhrases: [
      "what commands are available?",
      "show me what i can ask",
      "what can i ask you?",
      "command help",
    ],
  },
  {
    id: "channels.discord_setup",
    command: "show setup for extension Discord",
    intentClass: "app_read",
    aliases: [
      "show setup for discord",
      "how do i set up discord",
      "how do i wire up discord",
      "discord setup",
      "set up discord",
    ],
    domains: ["channels"],
    keywords: ["discord", "setup", "bot token", "wire"],
    surfaceDescription: "Discord channel setup instructions",
  },
  {
    id: "channels.whatsapp_setup",
    command: "show setup for extension WhatsApp",
    intentClass: "app_read",
    aliases: [
      "show setup for whatsapp",
      "how do i set up whatsapp",
      "how do i wire up whatsapp",
      "whatsapp setup",
      "set up whatsapp",
    ],
    domains: ["channels"],
    keywords: ["whatsapp", "setup", "pair", "qr"],
    surfaceDescription: "WhatsApp channel setup and pairing instructions",
  },
  {
    id: "channels.slack_setup",
    command: "show setup for extension Slack",
    intentClass: "app_read",
    aliases: [
      "show setup for slack",
      "how do i set up slack",
      "how do i wire up slack",
      "slack setup",
      "set up slack",
    ],
    domains: ["channels"],
    keywords: ["slack", "setup", "bot token", "app token"],
    surfaceDescription: "Slack channel setup instructions",
  },
  {
    id: "channels.bluebubbles_setup",
    command: "show setup for extension BlueBubbles",
    intentClass: "app_read",
    aliases: [
      "show setup for bluebubbles",
      "how do i set up bluebubbles",
      "how do i wire up bluebubbles",
      "bluebubbles setup",
      "set up bluebubbles",
      "imessage setup",
      "how do i set up imessage",
    ],
    domains: ["channels"],
    keywords: ["bluebubbles", "imessage", "setup", "bridge", "server"],
    surfaceDescription: "BlueBubbles (iMessage) channel setup instructions",
  },
  {
    id: "channels.googlechat_setup",
    command: "show setup for extension GoogleChat",
    intentClass: "app_read",
    aliases: [
      "show setup for google chat",
      "how do i set up google chat",
      "how do i wire up google chat",
      "google chat setup",
      "set up google chat",
    ],
    domains: ["channels"],
    keywords: ["google chat", "googlechat", "webhook", "oauth"],
    surfaceDescription: "Google Chat channel setup and OAuth instructions",
  },
  {
    id: "channels.teams_setup",
    command: "show setup for extension Teams",
    intentClass: "app_read",
    aliases: [
      "show setup for teams",
      "how do i set up teams",
      "how do i wire up teams",
      "teams setup",
      "set up microsoft teams",
      "microsoft teams setup",
    ],
    domains: ["channels"],
    keywords: ["teams", "microsoft teams", "app id", "service url"],
    surfaceDescription: "Microsoft Teams channel setup instructions",
  },
  {
    id: "channels.doctor",
    command: "check channel health",
    intentClass: "app_read",
    aliases: [
      "check channel health",
      "run channel doctor",
      "diagnose channels",
      "channel diagnostics",
      "check channel setup",
      "are my channels working",
      "diagnose my channel setup",
      "channel health check",
      "run channel health check",
      "check oauth status",
      "channel setup status",
    ],
    domains: ["channels"],
    keywords: ["channel health", "doctor", "diagnose", "diagnostic", "repair", "oauth"],
    surfaceDescription: "channel health diagnostics, setup issues, and repair guidance for all channels",
    defaultForDomain: false,
    examplePhrases: [
      "check channel health",
      "run channel doctor",
      "diagnose channels",
      "are my channels working?",
    ],
  },
  {
    id: "channels.pairing.list",
    command: "list pending pairing requests",
    intentClass: "app_read",
    aliases: [
      "list pending pairing requests",
      "show pairing requests",
      "list pairing requests",
      "show pending pairings",
      "who is waiting to pair",
    ],
    domains: ["channels"],
    keywords: ["pairing", "pair", "pending pairing", "approve pairing"],
    surfaceDescription: "pending channel pairing requests waiting for operator approval",
  },
];

export const BUILTIN_INTENT_ALLOWED_COMMANDS = Array.from(
  new Set(BUILTIN_INTENTS.map((entry) => entry.command)),
);

export const BUILTIN_INTENT_MODEL_EXAMPLES = BUILTIN_INTENTS.flatMap((entry) =>
  (entry.examplePhrases ?? []).map((phrase) => ({ phrase, command: entry.command })),
);

export const BUILTIN_INTENT_SURFACE_DESCRIPTIONS = BUILTIN_INTENTS
  .filter((entry) => entry.surfaceDescription)
  .map((entry) => `${entry.command} — ${entry.surfaceDescription}`);

export const BUILTIN_INTENT_ROUTER_CARDS = BUILTIN_INTENTS.map((entry) => {
  const lines = [
    `${entry.command} — ${entry.surfaceDescription || entry.id}`,
    entry.useWhen?.length ? `use when: ${entry.useWhen.join(", ")}` : "",
    entry.notWhen?.length ? `not when: ${entry.notWhen.join(", ")}` : "",
    entry.confusableWith?.length ? `confusable with: ${entry.confusableWith.join(", ")}` : "",
    entry.contrastNotes?.length ? `notes: ${entry.contrastNotes.join(" | ")}` : "",
  ].filter(Boolean);
  return lines.join(" | ");
});

export const BUILTIN_DOMAIN_DEFAULTS = new Map<AppControlDomain, string>(
  BUILTIN_INTENTS.flatMap((entry) =>
    entry.defaultForDomain
      ? entry.domains.map((domain) => [domain, entry.command] as const)
      : [],
  ),
);

export type CommandPaletteEntry = {
  label: string;
  command: string;
  examplePhrase: string;
  domain: AppControlDomain | null;
  isMutating: boolean;
};

const DOMAIN_DISPLAY: Partial<Record<AppControlDomain | string, string>> = {
  board: "Boards & Tasks",
  workflow: "Workflows",
  scheduler: "Automations",
  agent: "Agents",
  channels: "Channels",
  extensions: "Extensions",
  skills: "Skills",
  memory: "Memory",
  dashboard: "Dashboard",
  activity: "Activity",
  approvals: "Approvals",
  logs: "Logs",
  debug: "Debug",
  maintenance: "Maintenance",
  security: "Security",
  metrics: "Metrics",
  usage: "Usage",
  settings: "Settings",
  council: "Council",
  hierarchy: "Hierarchy / Orgs",
  tags: "Tags",
  docs: "Docs & Data Sources",
  live: "Live",
  checkpoint: "Checkpoints",
};

export function getCommandPaletteEntries(): CommandPaletteEntry[] {
  const seen = new Set<string>();
  return BUILTIN_INTENTS.filter((entry) => {
    if (seen.has(entry.command)) return false;
    seen.add(entry.command);
    return true;
  }).map((entry) => ({
    label: entry.surfaceDescription || entry.command,
    command: entry.command,
    examplePhrase: entry.examplePhrases?.[0] || entry.aliases[0] || entry.command,
    domain: entry.domains[0] || null,
    isMutating: false,
  }));
}

export function getCommandPaletteText(): string {
  const entries = getCommandPaletteEntries();
  const byDomain = new Map<string, CommandPaletteEntry[]>();
  for (const entry of entries) {
    const domain = entry.domain || "general";
    const list = byDomain.get(domain) ?? [];
    list.push(entry);
    byDomain.set(domain, list);
  }
  const lines: string[] = ["## Available commands", ""];
  const orderedDomains: (AppControlDomain | string)[] = [
    "board", "workflow", "scheduler", "agent", "channels", "extensions", "skills",
    "memory", "docs", "hierarchy", "council", "dashboard", "activity", "approvals",
    "logs", "debug", "maintenance", "security", "metrics", "usage", "settings",
    "tags", "live", "checkpoint", "general",
  ];
  for (const domain of orderedDomains) {
    const domainEntries = byDomain.get(domain);
    if (!domainEntries?.length) continue;
    const displayName = DOMAIN_DISPLAY[domain] || domain;
    lines.push(`**${displayName}**`);
    for (const entry of domainEntries) {
      lines.push(`- ${entry.examplePhrase}`);
    }
    lines.push("");
  }
  lines.push("Tip: Ask in plain English. Most surfaces have multiple phrasing options.");
  return lines.join("\n");
}
